[project]
name = "hass-aliyun-bailian-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dashscope>=1.25.5",
    "homeassistant==2025.12.5",
]
